name: Main

on:
  push:
    branches:
      - main

jobs:
  Publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Bump version in the package.json
        run: npm version --no-git-tag-version minor

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: "Commit change"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump the version [skip ci]
